project_name: slc

before:
  hooks:
    - rm -rf ./dist
    - go mod tidy
    - git push
    - git push --tags
builds:
  -
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X github.com/sikalabs/slc/version.Version=v{{.Version}}
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - '6'
      - '7'
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: "arm"
      - goos: windows
        goarch: "arm64"
      - goos: linux
        goarch: arm
        goarm: 6
    binary: slc

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  prerelease: auto
  extra_files:
    - glob: ./dist/slc_windows_amd64_v1/slc.exe

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

brews:
  -
    name: slc
    tap:
      owner: sikalabs
      name: homebrew-tap
    skip_upload: auto
    homepage: https://github.com/sikalabs/slc
    url_template: "https://github.com/sikalabs/slc/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    folder: Formula
    caveats: "How to use this binary: https://github.com/sikalabs/slc"
    description: "SikaLabs Cloud CLI"
    install: |
      bin.install "slc"
    test: |
      system "#{bin}/slc version"

dockers:
    -
      goos: linux
      goarch: amd64
      image_templates:
        - "sikalabs/slc:{{ .Tag }}"
        - "ghcr.io/sikalabs/slc:{{ .Tag }}"
      dockerfile: Dockerfile.goreleaser
      ids:
        - slc
      build_flag_templates:
        - "--platform=linux/amd64"
        - "--label=org.opencontainers.image.created={{.Date}}"
        - "--label=org.opencontainers.image.title={{.ProjectName}}"
        - "--label=org.opencontainers.image.revision={{.FullCommit}}"
        - "--label=org.opencontainers.image.version={{.Version}}"
        - "--label=org.opencontainers.image.source=https://github.com/sikalabs/slc"
        - "--label=org.label-schema.schema-version=1.0"
        - "--label=org.label-schema.version={{.Version}}"
        - "--label=org.label-schema.name={{.ProjectName}}"
        - "--label=com.github.actions.name={{.ProjectName}}"
        - "--label=repository=https://github.com/sikalabs/slc"
        - "--label=maintainer=SikaLabs <opensource@sikalabs.com>"
    - goos: linux
      goarch: arm64
      image_templates:
        - "sikalabs/slc:{{ .Tag }}-arm64v8"
        - "ghcr.io/sikalabs/slc:{{ .Tag }}-arm64v8"
      dockerfile: Dockerfile.goreleaser.arm64v8
      ids:
        - slc
      build_flag_templates:
        - "--platform=linux/arm64"
        - "--label=org.opencontainers.image.created={{.Date}}"
        - "--label=org.opencontainers.image.title={{.ProjectName}}"
        - "--label=org.opencontainers.image.revision={{.FullCommit}}"
        - "--label=org.opencontainers.image.version={{.Version}}"
        - "--label=org.opencontainers.image.source=https://github.com/sikalabs/slc"
        - "--label=org.label-schema.schema-version=1.0"
        - "--label=org.label-schema.version={{.Version}}"
        - "--label=org.label-schema.name={{.ProjectName}}"
        - "--label=com.github.actions.name={{.ProjectName}}"
        - "--label=repository=https://github.com/sikalabs/slc"
        - "--label=maintainer=SikaLabs <opensource@sikalabs.com>"

changelog:
  filters:
    exclude:
      - '^VERSION'

scoop:
  bucket:
    owner: sikalabs
    name: scoop-bucket
  homepage:  https://github.com/sikalabs/slc
  description: SikaLabs Utils
  license: MIT
